In [1]:
import tensorflow as tf
print(('Your Tensorflow version: {0}').format(tf.__version__))

Your Tensorflow version: 2.5.0


In [3]:
# Create a constant tensor A
A = tf.constant([[4,3],
                 [6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [5]:
# Create a variable tensor V
V = tf.Variable([[3,1],
                 [4,5]])
# Create another tensor B
B = tf.constant([[7,8],
                 [4,5]])
print(V)
print(B)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [4, 5]], dtype=int32)>
tf.Tensor(
[[7 8]
 [4 5]], shape=(2, 2), dtype=int32)


In [6]:
# Concatenate columns
AB_concatenated = tf.concat(values=[A,B], axis=1)
AB_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]], dtype=int32)>

In [7]:
# Concatenate rows
AB_concatenated = tf.concat(values=[A,B], axis=0)
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [7, 8],
       [4, 5]], dtype=int32)>

In [11]:
# Usually we initialize tensors with random numbers
# But use 0s and 1s for masking
tensor = tf.zeros(shape=[3,4], dtype=tf.int32)
print(tensor)
tensor = tf.ones(shape=[3,4], dtype=tf.int32)
print(tensor)
tensor = tf.random.uniform(shape=[3,4], dtype=tf.float32)
print(tensor)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[0.37793577 0.05848992 0.9313886  0.64358854]
 [0.8564768  0.43852234 0.96035314 0.484033  ]
 [0.9751936  0.63782823 0.10739052 0.5677314 ]], shape=(3, 4), dtype=float32)


In [12]:
reshaped_tensor = tf.reshape(tensor=tensor, shape=[4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.37793577, 0.05848992, 0.9313886 ],
       [0.64358854, 0.8564768 , 0.43852234],
       [0.96035314, 0.484033  , 0.9751936 ],
       [0.63782823, 0.10739052, 0.5677314 ]], dtype=float32)>

In [13]:
tensor = tf.constant([[4.6, 4.2],
                      [7.5, 3.6], 
                      [2.7, 9.4],
                      [6.7, 8.3]], 
                      dtype=tf.float32)
tensor_as_int = tf.cast(tensor, tf.int32)
print(tensor)
print(tensor_as_int)

tf.Tensor(
[[4.6 4.2]
 [7.5 3.6]
 [2.7 9.4]
 [6.7 8.3]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[4 4]
 [7 3]
 [2 9]
 [6 8]], shape=(4, 2), dtype=int32)


In [14]:
# Notice this is a true transpose
# whereas reshape simply reshaped it 'linearly'
a = tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 7, 2, 6],
       [4, 3, 9, 8]], dtype=int32)>

In [15]:
A = tf.constant([[5, 8],
                 [3, 9]])

v = tf.constant([[4],[2]])

Av = tf.matmul(A,v)
Av

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]], dtype=int32)>

In [17]:
Av = tf.multiply(A, v)
Av

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 32],
       [ 6, 18]], dtype=int32)>

In [22]:
# Create an identity matrix
A = tf.constant([[4, 9], [5, 6], [1, 8]])
rows, columns = A.shape
print('rows: {0}, columns: {1}'.format(rows, columns))
A_identity = tf.eye(num_rows=rows, num_columns=columns, dtype=tf.int32)
print(A_identity)

rows: 3, columns: 2
tf.Tensor(
[[1 0]
 [0 1]
 [0 0]], shape=(3, 2), dtype=int32)
